# Generated by Django 5.2.1 on 2025-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
