# Generated by Django 5.2.1 on 2025-05-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_metric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
