# Generated by Django 5.2.1 on 2025-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_alter_metric_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='instance',
            field=models.CharField(default='localhost:8000', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='job',
            field=models.CharField(default='django', max_length=100),
        ),
    ]
