# Generated by Django 5.2.1 on 2025-05-19 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_metric_instance_metric_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertrule',
            old_name='notify_email',
            new_name='notification_email',
        ),
        migrations.RenameField(
            model_name='alertrule',
            old_name='critical_threshold',
            new_name='threshold',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='warning_threshold',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='comparator',
            field=models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('==', 'Equal to')], default='>', max_length=10),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Duration for which the condition must hold'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='metric_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
