# Generated by Django 5.2.1 on 2025-05-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0005_rename_notify_email_alertrule_notification_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertrule',
            old_name='threshold',
            new_name='critical_threshold',
        ),
        migrations.RenameField(
            model_name='alertrule',
            old_name='notification_email',
            new_name='notify_email',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='comparator',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='metric_name',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='severity',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring_app.metric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='warning_threshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
