# Generated by Django 5.2.1 on 2025-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0007_metricvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricvalue',
            name='prometheus_query',
            field=models.CharField(default=1, help_text='The PromQL query to fetch this metric', max_length=255),
            preserve_default=False,
        ),
    ]
